name: DO Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Copy files
        uses: appleboy/ssh-action@master
        env:
          DEPLOYDIR: "/var/www/hermesgarcia.com/public_html"
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd repositories/hermesgarcia.com
            git pull origin
            echo "Update repo"
            cp *.html $DEPLOYDIR
            cp robots.txt $DEPLOYDIR
            cp sitemap.xml $DEPLOYDIR
            cp .htaccess $DEPLOYDIR
            cp -R blog/ $DEPLOYDIR
            cp -R contactform/ $DEPLOYDIR
            cp -R css/ $DEPLOYDIR
            cp -R img/ $DEPLOYDIR
            cp -R js/ $DEPLOYDIR
            cp -R lib/ $DEPLOYDIR
